# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Kiddy.today Journal
title: Kiddy today 
email: your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "https://kiddy.today" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

github:  https://github.com/RamizIb
telegram: foo
instagram: bar

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  parse_span_html: true
  auto_ids: false

# Exclude
exclude:
  - package.json
  - package-lock.json
  - gulpfile.js
  - node_modules/

# Excerpt post separator
excerpt_separator: <!--more-->

# Sass compresed
sass:
    style: compressed

# Sitemap generator
sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/css/main.scss"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"